<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Serilog.Sinks.File\Serilog.Sinks.File.csproj" />
  </ItemGroup>

</Project>

